[package]
name = "cargo_metadata"
version = "0.1.1"
authors = ["Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>"]
repository = "https://github.com/oli-obk/cargo_metadata"
description = "structured access to the output of `cargo metadata`"
license = "MIT"

[dependencies]
serde = "0.9.1"
serde_json = "0.9.1"
serde_derive = "0.9.1"
