[package]
name = "cargo_metadata"
version = "0.2.3"
authors = ["Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>"]
repository = "https://github.com/oli-obk/cargo_metadata"
description = "structured access to the output of `cargo metadata`"
license = "MIT"

[dependencies]
error-chain = "0.10.0"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"

[dev-dependencies]
clap = "2.26.0"
docopt = "0.8.1"
